### ISSUE TITLE
Request: Modification of terms

### ISSUE THREAD

**Issue by wehddn** [AdamWhiteHat/GenericMultivariatePolynomial#1]
**Proposal/Summary**
I work with this library and use polynomials with double. After arithmetic operations, I often get "ugly" floating point values, for example 0.7000000000000001. I would like to be able to modify the terms of the polynomial to manually change the values

**Implementation**
In the library, the terms are stored as an array for which the get function is implemented, respectively, the set function could be added.

**Comment by AdamWhiteHat** [comment]
Hmm, yeah, I'm not sure why I made the coefficient get-only.
But I don't see any issue with allowing the Term.CoEfficient to be set, especially considering how cumbersome it is to properly instantiate a new Term to replace one.

So I went ahead and made that change and pushed it to the master branch. I went ahead and published a new version of the assembly with this change included to nuget.org, so you can just grab the latest version, [ver. 2023.63.1826 on nuget.org](https://www.nuget.org/packages/ExtendedArithmetic.GenericMultivariatePolynomial/2023.63.1826) or update your references from inside your project with the nuget package manager and begin using the new changes immediately.

The library now allows syntax like:
```csharp
var poly = MultivariatePolynomial<double>.Parse("5.7000000000001*X - 3*Y - 2*Z");
Console.WriteLine($"Polynomial: {poly}");

poly.Terms[0].CoEfficient = Math.Round(poly.Terms[0].CoEfficient, 5); // This was not allowed before
Console.WriteLine($"Modified polynomial: {poly}");

// Prints:
// Polynomial: 5.7000000000001*X - 2*Z - 3*Y
// Modified polynomial: 5.7*X - 2*Z - 3*Y
```

And you were always allowed to replace the term outright, as below:
```csharp
var variables = poly.Terms[0].Variables;
poly.Terms[0] = new Term<double>(Math.Round(poly.Terms[0].CoEfficient, 5), variables);
```
Although, as I say, this was rather cumbersome, only made bearable by copying the variables over, as shown, to avoid having to construct those anew, which was the most laborious part, in my opinion.


**IMPORTANT NOTE:**
Due to a previous bug-fix that I had checked in, but did not publish to nuget, the order in which the polynomial stores it's terms have changed; They are stored in reverse order than they previously were. To go along with this, I reversed the order in which the terms are printed when calling ToString(). Hopefully the change to the ToString() will result in the class printing the polynomial much in the same way as it was before, but it does impact anybody who was addressing terms by their index (`
poly.Terms[0] = ...`), so if you have any code that uses the indexer on the Polynomial.Terms array, you'll need to double check the that code and probably use the inverse index value.
I hate to do this, but it needed done and I figured now was a good time, as only 89 people have downloaded this new library so far, which is really tiny. Compare that to the thousands who have downloaded my univalent polynomial library.

This was necessary in order to fix a bug with polynomial division, since consistent monomial ordering is required for consistent and reliable multivariate polynomial division and multiplication (indeed; Multiplying two multivariate polynomials together can produce two wildly different results, both of which are valid,depending on which strict monomial ordering scheme you have chosen for your polynomial--multiplication and division of multivariate polynomials without this ordering scheme is ill defined).

I hope this doesn't impact you too much. I'm hoping addressing the terms by index was not too useful for you before this change that allows you to modify the CoEfficient, and that you weren't using it too much.

Let me know if this fix works for you, or if you encounter other problems or have any questions. Feel free to close the issue if you are satisfied with this fix. Otherwise, I will close it myself in a few days if I don't hear back from you.
